# Ten plik definiuje kroki kompilacji dla Google Cloud Build.
# Jest używany do automatycznego budowania i wdrażania aplikacji Firebase.

# Określamy, że logi z tej kompilacji mają być wysyłane tylko do Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Krok 0: Zainstaluj zależności Firebase CLI
  # Nadal instalujemy firebase-tools globalnie.
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Firebase CLI'
    args: ['install', '-g', 'firebase-tools']

  # Krok 1: Zainstaluj zależności projektu (jeśli masz plik package.json)
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Project Dependencies'
    args: ['install']

  # Krok 2: Zbuduj projekt (jeśli jest to aplikacja frontendowa)
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Project'
    args: ['run', 'build'] # Zmień 'build' na odpowiednią komendę, np. 'prod'

  # Krok 3: Wdróż na Firebase Hosting
  # Używamy bash, aby wykonać komendę firebase.
  - name: 'gcr.io/cloud-builders/npm' # Nadal używamy obrazu npm
    id: 'Deploy to Firebase Hosting'
    entrypoint: 'bash' # <-- KLUCZOWA ZMIANA: Używamy 'bash' jako punktu wejścia
    args:
      - '-c' # Argument dla bash, aby wykonać następny argument jako komendę
      - 'firebase deploy --only hosting --project $PROJECT_ID' # <-- KLUCZOWA ZMIANA: Cała komenda jako jeden string
    # Jeśli masz wiele projektów Firebase lub niestandardową konfigurację,
    # możesz potrzebować `--project=your-firebase-project-id` zamiast `$PROJECT_ID`.
    # Jeśli używasz wielu celów hostingowych:
    # args:
    #   - '-c'
    #   - 'firebase deploy --only hosting:your-hosting-target --project $PROJECT_ID'

# Opcjonalnie: Zapisz artefakty (np. zbudowane pliki) do Cloud Storage
# artifacts:
#   objects:
#     location: 'gs://your-artifact-bucket/builds/$BUILD_ID'
#     paths: ['build/**']
