# Ten plik definiuje kroki kompilacji dla Google Cloud Build.
# Jest używany do automatycznego budowania i wdrażania aplikacji Firebase.

# Określamy, że logi z tej kompilacji mają być wysyłane tylko do Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Krok 0: Usunęliśmy globalną instalację Firebase CLI.
  # Teraz zainstalujemy firebase-tools jako lokalną zależność w kroku 1.

  # Krok 1: Zainstaluj zależności projektu ORAZ firebase-tools lokalnie
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Project Dependencies and Firebase CLI' # Zmieniona nazwa kroku
    args: ['install', 'firebase-tools'] # Dodajemy 'firebase-tools' do lokalnych zależności

  # Krok 2: Zbuduj projekt (jeśli jest to aplikacja frontendowa)
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Project'
    args: ['run', 'build'] # Zmień 'build' na odpowiednią komendę, np. 'prod'

  # Krok 3: Wdróż na Firebase Hosting
  # Używamy npx, który powinien znaleźć lokalnie zainstalowane firebase-tools.
  - name: 'gcr.io/cloud-builders/npm' # Nadal używamy obrazu npm
    id: 'Deploy to Firebase Hosting'
    entrypoint: 'npx' # <-- KLUCZOWA ZMIANA: Używamy 'npx'
    args:
      - 'firebase' # Komenda, którą npx ma uruchomić
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '$PROJECT_ID' # Zmienna środowiskowa Cloud Build dla ID projektu
    # Jeśli masz wiele projektów Firebase lub niestandardową konfigurację,
    # możesz potrzebować `--project=your-firebase-project-id` zamiast `$PROJECT_ID`.
    # Jeśli używasz wielu celów hostingowych:
    # args:
    #   - 'firebase'
    #   - 'deploy'
    #   - '--only'
    #   - 'hosting:your-hosting-target'
    #   - '--project'
    #   - '$PROJECT_ID'

# Opcjonalnie: Zapisz artefakty (np. zbudowane pliki) do Cloud Storage
# artifacts:
#   objects:
#     location: 'gs://your-artifact-bucket/builds/$BUILD_ID'
#     paths: ['build/**']
